dist: bionic
language: generic
os: osx
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++ CC=gcc
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++ CC=clang

script: make merlin-link

compiler:
  - clang
  - gcc

