name: Make

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: brew
      if: matrix.os == 'macos-latest'
      shell: bash
      run: brew install re2c

    - name: apt-get
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: sudo apt-get -y install re2c

    - name: make
      run: make all
